plugins {
	id 'java'
	id 'jacoco'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.exercises'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

jacoco {
	toolVersion = '0.8.14'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.mapstruct:mapstruct:1.6.3'
	implementation 'org.springframework.boot:spring-boot-starter-security:4.1.0'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:4.1.0'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
	testImplementation 'org.testcontainers:postgresql:1.21.3'
	testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jacocoTestReport {
	dependsOn test
    reports {
        xml.required = false
        csv.required = false
		html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }

	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it).exclude("com/exercises/exeercises/model/**")
		}))
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				counter = 'LINE'
				value = 'COVEREDRATIO'
				minimum = 0.7
			}
		}
	}
}

test {
	finalizedBy jacocoTestReport
}

tasks.named('test') {
	useJUnitPlatform()
}

check.dependsOn jacocoTestCoverageVerification
