spring.application.name=exeercises
spring.sql.init.platform = postgres
spring.datasource.url=jdbc:postgresql://ep-icy-morning-aso4f2pu-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password = npg_Dap3Hbq5wenM
spring.jpa.hibernate.ddl-auto = update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

security.jwt.secret-key:${JWT_SECRET:0NTYVZMEIYkyZgzmv6cbPxJY7iLw5RuW6khiUAtmO7q}

