name: Frontend JavaScript CI

on:
  push:
    branches: ['**']
  pull_request: 
    branches: [main]
    paths: 
      - 'src/main/resources/static/**'
  schedule: 
    - cron: "0 3 * * *"

jobs: 
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node JS
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm' 
          cache-dependency-path: 'src/main/resources/static/package-lock.json'
      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

